{
    "name": "ELMOGPS Management",
    "version": "18.0.1.0.0",
    "category": "Operations / Fleet Tracking",
    "summary": "Integrated ELMOGPS commercial and operational management for Odoo 18",
    "description": """
ELMOGPS all-in-one management module for customers, contracts, GPS devices,
SIM cards, installations, maintenance, and outbound integration events.
    """,
    "author": "GeniusStep",
    "website": "https://github.com/geniustep/elmogps_odoo",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "sale_management",
        "stock",
        "purchase",
        "account",
        "maintenance",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequences.xml",
        "data/product_data.xml",
        "data/integration_data.xml",
        "data/cron.xml",
        "views/res_partner_views.xml",
        "views/stock_lot_views.xml",
        "views/contract_views.xml",
        "views/vehicle_views.xml",
        "views/installation_views.xml",
        "views/maintenance_views.xml",
        "views/integration_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
        "reports/installation_reports.xml",
    ],
    "assets": {},
    "installable": True,
    "application": True,
    "auto_install": False,
}
