from . import res_partner
from . import res_company
from . import res_config_settings
from . import product_template
from . import stock_lot
from . import sale_order
from . import contract
from . import vehicle_reference
from . import installation
from . import maintenance_request
from . import integration_event
from . import integration_log
